# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearbyFavourites' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NearbyFavourites
  pod 'GooglePlaces', '2.1'
  pod 'GoogleMaps', '2.1'
  pod 'GooglePlacePicker', '2.1'

  target 'NearbyFavouritesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
